### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by trpham** [trpham/ToDoApp#1]
My app is complete, please review. 
Please let's me know if you have any questions (phamcse@berkeley.edu)
@codepathreview @codepath

**Comment by nesquena** [comment]
Hi Truong,

Thanks for applying and submitting your pre-work. Based on your LinkedIn it doesn't look like you meet the selection criteria for participating in the course. In particular:

* 1+ years of professional software development experience in a single role (shipping code to production and collaborating on a team strongly preferred)

If not, since you applied I can add you to our remote self-paced observer group so you will still have access to the curriculum and can learn at your own pace. In the meantime, you should also check out the [resources we provide here as well](http://courses.codepath.com/snippets/intro_to_android/email_faq#heading-i-dont-have-much-or-any-professional-software-development-experience-how-can-codepath-help-me).

**Comment by trpham** [comment]
Hi CodePath,

I'm not sure if that's a strict requirement, but through academic activities and internships, I have had many software development experience. Other than that, I'm qualify for many CodePath evaluation criteria and most importantly, I have the big dreams and passion to learn.

I believe that I can better handle the workload of this course which can be proven by the TodoApp I completed in a week without having any prior Android Development experience.

I'm very passionate about this program and this opportunity is important to me. Therefore, I'm so hoping that I can get in.

**Comment by nesquena** [comment]
Hi Truong,

Thanks for the explanation and clarification. We'll be considering you for the course but note that we've had many applicants and we weight based largely on past experience and on the quality and completeness of the pre-work. As a result, I would definitely encourage you to continue to work on your submission although it's already looking pretty solid. If you don't end up being selected as a participant, rest assured we'll still provide you access to the content as an observer so you'll be able to ramp up on Android either way.

**Comment by trpham** [comment]
Thank you CodePath,

Since there are still 4 days left, I will try to work on more features for the app.

**Comment by trpham** [comment]
Hi CodePath,
I have implement more tasks for the app. Please check it out. Hope you like it.
@codepathreview @codepath

Also you asked, I wish to get selected for the program because I want to have a training record which make me feel good about. And most importantly, I found myself a better motivation and therefore learn things better under commitment.

**Comment by nesquena** [comment]
Great, thanks for the update and glad to see you got a number of optionals implemented. We will be determining final admittance into the program over the next couple weeks. For those not admitted as participants, we will offer access to applicants as a remote observer cohort that has access to the materials and is able to work on the projects at their own pace. You will be hearing from us again soon.
